//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenteApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VenteApp.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        internal static string ActionsLabel {
            get {
                return ResourceManager.GetString("ActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un client.
        /// </summary>
        internal static string AddClientButton {
            get {
                return ResourceManager.GetString("AddClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un produit.
        /// </summary>
        internal static string AddProductButton {
            get {
                return ResourceManager.GetString("AddProductButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un Fournisseur.
        /// </summary>
        internal static string AddProviderButton {
            get {
                return ResourceManager.GetString("AddProviderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string AddressPlaceholder {
            get {
                return ResourceManager.GetString("AddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un utilisateur.
        /// </summary>
        internal static string AddUserButton {
            get {
                return ResourceManager.GetString("AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vente App.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panier.
        /// </summary>
        internal static string BasketLabel {
            get {
                return ResourceManager.GetString("BasketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panier.
        /// </summary>
        internal static string BasketTitle {
            get {
                return ResourceManager.GetString("BasketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Factures.
        /// </summary>
        internal static string BillingLabel {
            get {
                return ResourceManager.GetString("BillingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Factures.
        /// </summary>
        internal static string BillingsTitle {
            get {
                return ResourceManager.GetString("BillingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        internal static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        internal static string CategoryPlaceholder {
            get {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client :.
        /// </summary>
        internal static string ClientLabel {
            get {
                return ResourceManager.GetString("ClientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de Siret.
        /// </summary>
        internal static string ClientNumberLabel {
            get {
                return ResourceManager.GetString("ClientNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de Siret :.
        /// </summary>
        internal static string ClientNumberLabelFact {
            get {
                return ResourceManager.GetString("ClientNumberLabelFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le numéro Siret.
        /// </summary>
        internal static string ClientNumberPlaceholder {
            get {
                return ResourceManager.GetString("ClientNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un client.
        /// </summary>
        internal static string ClientPickerTitle {
            get {
                return ResourceManager.GetString("ClientPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients.
        /// </summary>
        internal static string ClientsLabel {
            get {
                return ResourceManager.GetString("ClientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients.
        /// </summary>
        internal static string ClientsTitle {
            get {
                return ResourceManager.GetString("ClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client.
        /// </summary>
        internal static string ClientTitle {
            get {
                return ResourceManager.GetString("ClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un utilisateur.
        /// </summary>
        internal static string CreateUserTitle {
            get {
                return ResourceManager.GetString("CreateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de bord.
        /// </summary>
        internal static string DashboardLabel {
            get {
                return ResourceManager.GetString("DashboardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de bord.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le {0/MM/yyyy HH}.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date :.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -.
        /// </summary>
        internal static string DecrementButton {
            get {
                return ResourceManager.GetString("DecrementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger PDF.
        /// </summary>
        internal static string DownloadAllPdfButton {
            get {
                return ResourceManager.GetString("DownloadAllPdfButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger le PDF des graphiques.
        /// </summary>
        internal static string DownloadChartsPdfButton {
            get {
                return ResourceManager.GetString("DownloadChartsPdfButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger PDF.
        /// </summary>
        internal static string DownloadPdfButton {
            get {
                return ResourceManager.GetString("DownloadPdfButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger PDF.
        /// </summary>
        internal static string DownloadPdfButton1 {
            get {
                return ResourceManager.GetString("DownloadPdfButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date fin :.
        /// </summary>
        internal static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre licence.
        /// </summary>
        internal static string EnterLicenseLabel {
            get {
                return ResourceManager.GetString("EnterLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer Licence.
        /// </summary>
        internal static string EnterLicenseTitle {
            get {
                return ResourceManager.GetString("EnterLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;expiration.
        /// </summary>
        internal static string ExpirationDateLabel {
            get {
                return ResourceManager.GetString("ExpirationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historiques.
        /// </summary>
        internal static string HistoricalLabel {
            get {
                return ResourceManager.GetString("HistoricalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Historiques.
        /// </summary>
        internal static string HistoricalTitle {
            get {
                return ResourceManager.GetString("HistoricalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +.
        /// </summary>
        internal static string IncrementButton {
            get {
                return ResourceManager.GetString("IncrementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventaires.
        /// </summary>
        internal static string InventoryLabel {
            get {
                return ResourceManager.GetString("InventoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventaires.
        /// </summary>
        internal static string InventoryTitle {
            get {
                return ResourceManager.GetString("InventoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facture.
        /// </summary>
        internal static string InvoiceTitle {
            get {
                return ResourceManager.GetString("InvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clé de licence.
        /// </summary>
        internal static string LicenseKeyPlaceholder {
            get {
                return ResourceManager.GetString("LicenseKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence.
        /// </summary>
        internal static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre licence expirera bientôt !.
        /// </summary>
        internal static string LicenseWarningText {
            get {
                return ResourceManager.GetString("LicenseWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page connexion.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string LoginPlaceholder {
            get {
                return ResourceManager.GetString("LoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        internal static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro.
        /// </summary>
        internal static string NumberLabel {
            get {
                return ResourceManager.GetString("NumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétaire.
        /// </summary>
        internal static string OwnerLabel {
            get {
                return ResourceManager.GetString("OwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page {0} de {Binding TotalPages}.
        /// </summary>
        internal static string PageLabel {
            get {
                return ResourceManager.GetString("PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un client.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de téléphone.
        /// </summary>
        internal static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Précédent.
        /// </summary>
        internal static string PreviousButton {
            get {
                return ResourceManager.GetString("PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de bord des produits.
        /// </summary>
        internal static string ProductDashboardTitle {
            get {
                return ResourceManager.GetString("ProductDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du produit.
        /// </summary>
        internal static string ProductDetailsTabTitle {
            get {
                return ResourceManager.GetString("ProductDetailsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du produit.
        /// </summary>
        internal static string ProductDetailsTitle {
            get {
                return ResourceManager.GetString("ProductDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produit.
        /// </summary>
        internal static string ProductLabel {
            get {
                return ResourceManager.GetString("ProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du Produit.
        /// </summary>
        internal static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produit.
        /// </summary>
        internal static string ProductPageTitle {
            get {
                return ResourceManager.GetString("ProductPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produits.
        /// </summary>
        internal static string ProductsLabel {
            get {
                return ResourceManager.GetString("ProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produits.
        /// </summary>
        internal static string ProductsLabel1 {
            get {
                return ResourceManager.GetString("ProductsLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produits.
        /// </summary>
        internal static string ProductsTitle {
            get {
                return ResourceManager.GetString("ProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string ProviderAddressLabel {
            get {
                return ResourceManager.GetString("ProviderAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du fournisseur.
        /// </summary>
        internal static string ProviderDetailsTabTitle {
            get {
                return ResourceManager.GetString("ProviderDetailsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string ProviderEmailLabel {
            get {
                return ResourceManager.GetString("ProviderEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom du fournisseur.
        /// </summary>
        internal static string ProviderFirstNameLabel {
            get {
                return ResourceManager.GetString("ProviderFirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du fournisseur.
        /// </summary>
        internal static string ProviderNameLabel {
            get {
                return ResourceManager.GetString("ProviderNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fournisseur.
        /// </summary>
        internal static string ProviderPageTitle {
            get {
                return ResourceManager.GetString("ProviderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de téléphone.
        /// </summary>
        internal static string ProviderPhoneLabel {
            get {
                return ResourceManager.GetString("ProviderPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un fournisseur.
        /// </summary>
        internal static string ProviderPickerTitle {
            get {
                return ResourceManager.GetString("ProviderPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produits du fournisseur.
        /// </summary>
        internal static string ProviderProductsTitle {
            get {
                return ResourceManager.GetString("ProviderProductsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fournisseurs.
        /// </summary>
        internal static string ProvidersLabel {
            get {
                return ResourceManager.GetString("ProvidersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fournisseurs.
        /// </summary>
        internal static string ProvidersTitle {
            get {
                return ResourceManager.GetString("ProvidersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé un fournisseur.
        /// </summary>
        internal static string ProviderTitle {
            get {
                return ResourceManager.GetString("ProviderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix d&apos;achat.
        /// </summary>
        internal static string PurchasePriceLabel {
            get {
                return ResourceManager.GetString("PurchasePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix d&apos;achat.
        /// </summary>
        internal static string PurchasePricePlaceholder {
            get {
                return ResourceManager.GetString("PurchasePricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantité.
        /// </summary>
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantité vendue.
        /// </summary>
        internal static string QuantitySoldLabel {
            get {
                return ResourceManager.GetString("QuantitySoldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôle.
        /// </summary>
        internal static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de vente.
        /// </summary>
        internal static string SaleDateLabel {
            get {
                return ResourceManager.GetString("SaleDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix de vente.
        /// </summary>
        internal static string SalePriceLabel {
            get {
                return ResourceManager.GetString("SalePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix de vente.
        /// </summary>
        internal static string SalePricePlaceholder {
            get {
                return ResourceManager.GetString("SalePricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes.
        /// </summary>
        internal static string SalesLabel {
            get {
                return ResourceManager.GetString("SalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total des ventes.
        /// </summary>
        internal static string SalesSummaryLabel {
            get {
                return ResourceManager.GetString("SalesSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total des ventes.
        /// </summary>
        internal static string SalesSummaryTitle {
            get {
                return ResourceManager.GetString("SalesSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes.
        /// </summary>
        internal static string SalesTitle {
            get {
                return ResourceManager.GetString("SalesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un client.
        /// </summary>
        internal static string SearchClientPlaceholder {
            get {
                return ResourceManager.GetString("SearchClientPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche par client ou total.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un produit.
        /// </summary>
        internal static string SearchProductPlaceholder {
            get {
                return ResourceManager.GetString("SearchProductPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un produit.
        /// </summary>
        internal static string SearchProductPlaceholder1 {
            get {
                return ResourceManager.GetString("SearchProductPlaceholder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un fournisseur.
        /// </summary>
        internal static string SearchProviderPlaceholder {
            get {
                return ResourceManager.GetString("SearchProviderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher une vente.
        /// </summary>
        internal static string SearchSalePlaceholder {
            get {
                return ResourceManager.GetString("SearchSalePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher un utilisateur.
        /// </summary>
        internal static string SearchUserPlaceholder {
            get {
                return ResourceManager.GetString("SearchUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez une date.
        /// </summary>
        internal static string SelectDatePlaceholder {
            get {
                return ResourceManager.GetString("SelectDatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher.
        /// </summary>
        internal static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produits.
        /// </summary>
        internal static string ShowProductsButton {
            get {
                return ResourceManager.GetString("ShowProductsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille.
        /// </summary>
        internal static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille.
        /// </summary>
        internal static string SizePlaceholder {
            get {
                return ResourceManager.GetString("SizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début :.
        /// </summary>
        internal static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stock.
        /// </summary>
        internal static string StockLabel {
            get {
                return ResourceManager.GetString("StockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stock.
        /// </summary>
        internal static string StockPlaceholder {
            get {
                return ResourceManager.GetString("StockPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 10 Produits les moins vendus.
        /// </summary>
        internal static string TopLeastSoldLabel {
            get {
                return ResourceManager.GetString("TopLeastSoldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top 10 Produits les plus vendus.
        /// </summary>
        internal static string TopMostSoldLabel {
            get {
                return ResourceManager.GetString("TopMostSoldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        internal static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantité Totale Vendue.
        /// </summary>
        internal static string TotalQuantitySoldLabel {
            get {
                return ResourceManager.GetString("TotalQuantitySoldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix Total des Ventes.
        /// </summary>
        internal static string TotalSalesPriceLabel {
            get {
                return ResourceManager.GetString("TotalSalesPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unité de mesure.
        /// </summary>
        internal static string UnitMeasureLabel {
            get {
                return ResourceManager.GetString("UnitMeasureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unité de mesure.
        /// </summary>
        internal static string UnitMeasurePlaceholder {
            get {
                return ResourceManager.GetString("UnitMeasurePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs.
        /// </summary>
        internal static string UsersLabel {
            get {
                return ResourceManager.GetString("UsersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs.
        /// </summary>
        internal static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider le panier.
        /// </summary>
        internal static string ValidateBasketButton {
            get {
                return ResourceManager.GetString("ValidateBasketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string ValidateButton {
            get {
                return ResourceManager.GetString("ValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir le panier.
        /// </summary>
        internal static string ViewBasketButton {
            get {
                return ResourceManager.GetString("ViewBasketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir.
        /// </summary>
        internal static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue dans l&apos;application VenteApp.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
